const mapToPayload = (sourceData) => {
  const payload = {
    OrgId: sourceData.OrgId,
    CVCode: sourceData.CVCode,
    BranchCode: sourceData.BranchCode || "00111",
    Email: sourceData.Email,
    Password: sourceData.Password,
    ConfirmPassword: sourceData.ConfirmPassword,
    SMSContactNumber: sourceData.SMSContactNumber,
    FullName: sourceData.FullName,
    ResidentAddress: sourceData.ResidentAddress,
    NricFin: sourceData.NricFin,
    Nationality: sourceData.Nationality,
    PassportNo: sourceData.PassportNo,
    PassportIssuePlace: sourceData.PassportIssuePlace,
    PassportExpiryDate: sourceData.PassportExpiryDate,
    PassportExpiryDateString: sourceData.PassportExpiryDateString,
    PassportIssueDate: sourceData.PassportIssueDate,
    PassportIssueDateString: sourceData.PassportIssueDateString,
    WPNo: sourceData.WPNo,
    WPExpiry: sourceData.WPExpiry,
    WPExpiryString: sourceData.WPExpiryString,
    Religion: sourceData.Religion,
    DateOfBirth: sourceData.DateOfBirth,
    DateOfBirthString: sourceData.DateOfBirthString,
    MaritalStatus: sourceData.MaritalStatus,
    BirthPlace: sourceData.BirthPlace,
    BirthPlaceString: sourceData.BirthPlaceString,
    Specialisation: sourceData.Specialisation,
    RepatraiteAirport: sourceData.RepatraiteAirport,
    Status: sourceData.Status,
    OtherInfo: sourceData.OtherInfo,
    DirectHire: sourceData.DirectHire,
    TrainingCenter: sourceData.TrainingCenter,
    Complexion: sourceData.Complexion,
    Height: sourceData.Height,
    Feet: sourceData.Feet || 0,
    Weight: sourceData.Weight,
    Pound: sourceData.Pound || 0,
    PlacementFee: parseInt(sourceData.PlacementFee) || 0,
    BasicSalary: sourceData.BasicSalary,
    offDayDailyRate: sourceData.offDayDailyRate,
    HelperFee: sourceData.HelperFee,
    Pocketmoney: sourceData.Pocketmoney,
    SelectOffDays: parseInt(sourceData.SelectOffDays) || 0,
    EnterOffDays: parseInt(sourceData.EnterOffDays),
    FatherOccupation: sourceData.FatherOccupation,
    MotherOccupation: sourceData.MotherOccupation,
    FatherAge: parseInt(sourceData.FatherAge),
    MotherAge: parseInt(sourceData.MotherAge),
    SiblingsPosition: sourceData.SiblingsPosition,
    NoOfBrother: parseInt(sourceData.NoOfBrother),
    NoOfSister: parseInt(sourceData.NoOfSister),
    BrotherAge: parseInt(sourceData.BrotherAge),
    SisterAge: parseInt(sourceData.SisterAge),
    HusbandName: sourceData.HusbandName,
    HusbandOccupation: sourceData.HusbandOccupation,
    HusbandAge: parseInt(sourceData.HusbandAge),
    NoofChildren: parseInt(sourceData.NoofChildren),
    ChildAge: parseInt(sourceData.ChildAge),
    Isactive: sourceData.Isactive,
    HelperCode: sourceData.HelperCode || sourceData.CVCode,
    Experience: sourceData.Experience,
    Interviewer: sourceData.Interviewer,
    PersonImageString: sourceData.PersonImageString,
    PersonImg_Base64String: sourceData.PersonImg_Base64String,
    PersonImageFileName: sourceData.PersonImageFileName,
    PersonImagePath: sourceData.PersonImagePath,
    FullImageString: sourceData.FullImageString,
    FullImg_Base64String: sourceData.FullImg_Base64String,
    FullImageFileName: sourceData.FullImageFileName,
    VideoFileName: sourceData.VideoFileName,
    VedioImagePath: sourceData.VedioImagePath,
    VedioFileName: sourceData.VedioFileName,
    Video: sourceData.Video,
    FullImagePath: sourceData.FullImagePath,
    CreatedBy: sourceData.CreatedBy || null,
    CreatedOn: sourceData.CreatedOn || new Date().toISOString(),
    ChangedBy: sourceData.ChangedBy || null,
    ChangedOn: sourceData.ChangedOn || new Date().toISOString(),
    CVNumber: sourceData.CVNumber,
    Contacts: sourceData.Contacts || [],
    Language: sourceData.Language || [],
    Educations: sourceData.Educations || [],
    Interview: sourceData.Interview || [],
    HelperExperience: sourceData.HelperExperience || [],
    SkillMaster: sourceData.SkillMaster || [],
    EvaluationofSkill: sourceData.EvaluationofSkill || [],
    MedicalCV: sourceData.MedicalCV || [],
    CustomUpload: sourceData.CustomUpload || [],
    HealthRestriction: sourceData.HealthRestriction || [],
    OtherRemarks: sourceData.OtherRemarks || [],
    HelperFamilyBackGround: sourceData.HelperFamilyBackGround || [],
    Specialization: sourceData.Specialization || [],
    Passport: sourceData.Passport || "",
    PassportFileName: sourceData.PassportFileName || "",
    PassportFileValueBase64: sourceData.PassportFileValueBase64 || "",
    PassportURL: sourceData.PassportURL || "",
    IdDocumentFileValue: sourceData.IdDocumentFileValue || "",
    IDDocumentFileName: sourceData.IDDocumentFileName || "",
    IDDocumentFileValueBase64: sourceData.IDDocumentFileValueBase64 || "",
    OtherDetailsFileValueBase64: sourceData.OtherDetailsFileValueBase64 || "",
    OtherDetailsFileName: sourceData.OtherDetailsFileName || "",
    BirthCertificateURL: sourceData.BirthCertificateURL || "",
    MarriageCertificate: sourceData.MarriageCertificate || "",
    MarriageCertificateFileName: sourceData.MarriageCertificateFileName || "",
    MarriageCertificateFileValueBase64: sourceData.MarriageCertificateFileValueBase64 || "",
    MarriageCertificateURL: sourceData.MarriageCertificateURL || "",
    FamilyCertificate: sourceData.FamilyCertificate || "",
    FamilyCertificateFileName: sourceData.FamilyCertificateFileName || "",
    FamilyCertificateFileValueBase64: sourceData.FamilyCertificateFileValueBase64 || "",
    FamilyCertificateURL: sourceData.FamilyCertificateURL || "",
    IsSingaporeExperiance: sourceData.IsSingaporeExperiance || false,
    RestDay: sourceData.RestDay,
    EntryDate: sourceData.EntryDate,
    TrainingCenterDate: sourceData.TrainingCenterDate,
    EntryDateString: sourceData.EntryDateString || "",
    TrainingCenterDateString: sourceData.TrainingCenterDateString || "",
    CVStatus: sourceData.CVStatus || null,
    ReligionName: sourceData.ReligionName,
    MonthlyOffDay: sourceData.MonthlyOffDay || null,
    Understandinglevel: sourceData.Understandinglevel || null,
    ExperienceCountry: sourceData.ExperienceCountry || null,
    CVDescription: sourceData.CVDescription || null,
    LoanTotalAmount: sourceData.LoanTotalAmount || null,
    TotalLoanDeduction: sourceData.TotalLoanDeduction,
    LoanBalanceAmount: sourceData.LoanBalanceAmount,
    FamilyChild: sourceData.FamilyChild || null,
    OtherRemark: sourceData.OtherRemark || null,
    skill1: sourceData.skill1,
    skill2: sourceData.skill2,
    skill3: sourceData.skill3,
    skill4: sourceData.skill4,
    skill5: sourceData.skill5,
    skill6: sourceData.skill6,
    skill7: sourceData.skill7,
    skill8: sourceData.skill8,
    skill9: sourceData.skill9,
    fdw1: sourceData.fdw1,
    fdw2: sourceData.fdw2,
    fdw3: sourceData.fdw3,
    fdw4: sourceData.fdw4,
    RemarksHeader: sourceData.RemarksHeader
  };

  return payload;
};

export default mapToPayload